# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('installs', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('developer', models.CharField(max_length=200)),
                ('developer_url', models.URLField()),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.App')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Category')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='cateogry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Category'),
        ),
        migrations.AddField(
            model_name='app',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.SubCategory'),
        ),
    ]
