# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeSubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('apps', models.ManyToManyField(to='cafe.App')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSubCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('apps', models.ManyToManyField(to='cafe.App')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.HomeCollection')),
            ],
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
