# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20190416_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='icon',
            field=models.URLField(default='http://google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_type',
            field=models.IntegerField(choices=[(1, 'app'), (2, 'game')], default=1),
            preserve_default=False,
        ),
    ]
