# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_auto_20190429_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeApps',
            fields=[
                ('cateogry', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('installs', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('developer', models.CharField(max_length=200)),
                ('developer_url', models.URLField()),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField()),
                ('icon', models.URLField()),
                ('rating_total', models.CharField(max_length=200)),
                ('rating_total_count', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='homesubcat',
            name='apps',
            field=models.ManyToManyField(to='cafe.HomeApps'),
        ),
        migrations.AlterField(
            model_name='homesubcollection',
            name='apps',
            field=models.ManyToManyField(to='cafe.HomeApps'),
        ),
    ]
