# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 21:16
from __future__ import unicode_literals

import cafe.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_auto_20190418_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='name',
            field=cafe.models.NameField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=cafe.models.NameField(max_length=100),
        ),
    ]
