# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_auto_20190429_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeApps',
            new_name='HomeApp',
        ),
    ]
