# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_auto_20190422_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='appurl',
            name='category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appurl',
            name='subcategory',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
