# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_auto_20190422_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='rating_total',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='rating_total_count',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='cateogry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='cafe.Category'),
        ),
        migrations.AlterField(
            model_name='app',
            name='installs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='app',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='cafe.SubCategory'),
        ),
        migrations.AlterField(
            model_name='app',
            name='version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='cafe.App'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cafe.Category'),
        ),
    ]
