# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_app_package_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='id',
        ),
        migrations.AlterField(
            model_name='app',
            name='package_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
