# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('packagename', models.CharField(max_length=200)),
                ('icon', models.URLField()),
                ('developer', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('installs', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RankCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RankFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='cafe.RankCat')),
            ],
        ),
        migrations.AddField(
            model_name='rankapp',
            name='rankcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='cafe.RankCat'),
        ),
        migrations.AddField(
            model_name='rankapp',
            name='rankfilter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='cafe.RankFilter'),
        ),
    ]
