# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='url',
            field=models.URLField(default='http://google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(default='http://google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='url',
            field=models.URLField(default='http://google.com'),
            preserve_default=False,
        ),
    ]
