# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20190501_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankapp',
            name='rankcategory',
        ),
    ]
