# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_remove_rankapp_rankcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankcat',
            name='url',
        ),
        migrations.RemoveField(
            model_name='rankfilter',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rankfilter',
            name='url',
        ),
        migrations.AddField(
            model_name='rankapp',
            name='rankcat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='cafe.RankCat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rankcat',
            name='catcode',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rankfilter',
            name='filtercode',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
