# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20190418_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category_type',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.IntegerField(choices=[(1, 'app'), (2, 'game')], default=1),
            preserve_default=False,
        ),
    ]
