# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_auto_20190501_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('developerID', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='app',
            name='developer_url',
        ),
        migrations.AlterField(
            model_name='app',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='cafe.Developer'),
        ),
    ]
