# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_auto_20190502_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedApp',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField()),
                ('icon', models.URLField()),
                ('rating_total', models.CharField(max_length=200)),
                ('rating_total_count', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cateogry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendedapps', to='cafe.Category')),
            ],
        ),
    ]
