# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_recommendedapp_app_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedapp',
            name='app_type',
            field=models.CharField(choices=[('recom', 'Recommended'), ('ad', 'Advertized')], max_length=200),
        ),
    ]
