# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_auto_20190521_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesubcat',
            name='apps',
            field=models.ManyToManyField(to='cafe.App'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
