# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_auto_20190422_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='package_name',
            field=models.CharField(default='com.google.com', max_length=200),
            preserve_default=False,
        ),
    ]
