# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_auto_20190422_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='app',
        ),
    ]
