# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_remove_screenshot_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='cafe.App'),
            preserve_default=False,
        ),
    ]
